[package]
name = "porty"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"]}
comfy-table = "7"
anyhow = "1"
nix = { version = "0.29", features = ["signal"] }
libc = "0.2"

